name: Build & Test (macos & linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
